/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.8.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MatchSimpleAlliances : A list of alliances, the teams on the alliances, and their score.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MatchSimpleAlliances {
    #[serde(rename = "red", skip_serializing_if = "Option::is_none")]
    pub red: Option<Box<crate::models::MatchAlliance>>,
    #[serde(rename = "blue", skip_serializing_if = "Option::is_none")]
    pub blue: Option<Box<crate::models::MatchAlliance>>,
}

impl MatchSimpleAlliances {
    /// A list of alliances, the teams on the alliances, and their score.
    pub fn new() -> MatchSimpleAlliances {
        MatchSimpleAlliances {
            red: None,
            blue: None,
        }
    }
}


